repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  -   id: check-yaml
      files: src/.*
  -   id: end-of-file-fixer
      files: src/.*
  -   id: trailing-whitespace
      files: src/.*

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: "isort:   sorts imports"
      files: src/.*

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  -   id: black
      name: "black:   formats python code"
      language_version: python3
      files: src/.*

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  -   id: flake8
      name: "flake8:  checks code style"
      additional_dependencies:
        - flake8-black>=0.1.1
      language_version: python3
      files: src/.*

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
    - id: bandit
      name: "bandit:  checks security issues"
      args: ["--quiet", "--skip", "B101", "test/"]
      files: src/.*
